# Generated by Django 4.1.4 on 2022-12-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("money_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="splits",
            old_name="transactions_id",
            new_name="transaction",
        ),
    ]
