# Generated by Django 4.1.4 on 2022-12-30 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("money_tracker", "0002_rename_transactions_id_splits_transaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Splits",
            new_name="Split",
        ),
        migrations.RenameModel(
            old_name="Transactions",
            new_name="Transaction",
        ),
    ]
