# Generated by Django 4.1.4 on 2022-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_tracker", "0003_rename_splits_split_rename_transactions_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="split",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
