# Generated by Django 4.1.4 on 2022-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_tracker", "0004_split_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(default="Split", max_length=64),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=256),
        ),
    ]
