# Generated by Django 4.1.4 on 2022-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_tracker", "0005_transaction_name_alter_transaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
